#!/bin/bash


### PARAMETRES ###

OPTIONS=( 
    "GXY_SAFE" 
    "GXY_MEGASAFE"
    )

prompt=""
for (( i = 0; i < ${#OPTIONS[@]}; i++ )); do
    if [[ "$(df -Hl | grep "/Volumes/${OPTIONS[$i]}")" != "" ]]; then
        prompt+="$((i+1)): ${OPTIONS[$i]}\n";
    fi
done

if [[ $prompt == "" ]]; then
    printf "ERROR: You have not device plugged in, please plug at least of these:\n"
    for (( i = 0; i < ${#OPTIONS[@]}; i++ )); do
        printf " - ${OPTIONS[$i]}\n";
    done
fi

USB_NAME=""
while [[ $USB_NAME == "" ]]; do
    printf "$prompt"
    read -r -n 1 resp
    if [[ $resp -ge 1 && $resp -le ${#OPTIONS[@]} ]]; then
        USB_NAME="${OPTIONS[$((resp-1))]}"
    else
        printf "\nError: mauvais input :-)\n"
    fi

    #if [[ $resp == "1" ]];then
        #USB_NAME="GXY_SAFE"
    #elif [[ $resp == "2" ]];then
        #USB_NAME="GXY_MEGASAFE"
    #else
        #printf "\nError: mauvais input :-)\n"
    #fi
done

echo ""
echo "The device that will be synced is \"$USB_NAME\""
echo ""

#USB_NAME="GXY_SAFE"

# Gather the intel from files.txt and reformat it (remove comments, remove
# trailing white spaces and remove empty lines)
intel=$(cat "./files.txt" | gsed -e "s/#.*$//;s/\s*$//;/^$/d;")

#originPrefix="$HOME"
destinationPrefix="/Volumes/$USB_NAME"
#destinationPrefix="/tmp/Yann"

### FUNCITON ###

copie() {
    cp "$1" "$2"
    #echo cp "$1" "$2"
}

remove_white_spaces(){
    echo "$1" | gsed -e "s/^\s*//;s/\s*$//"
}

### CODE ###

files=()
origin=""
destination=""

while IFS= read -r line;do # go through every line in intel
    # if the line contains "->" it means that it will indicate the origin and
    # the destination of the following files
    #if [[ $line == *"->"* ]]; then
        origin=$( remove_white_spaces "$(echo $line | awk -F "->" '{$0=$1}1')")
        destination=$destinationPrefix"/""${origin##*/}"
        #echo $destination
        #destination="$destinationPrefix/"$(remove_white_spaces "$(echo $line | awk -F "->" '{$0=$2}1' | cut -d ":" -f 1)")

        mkdir -p "$destination"
        copie "$origin" "$destination"
    #elif [[ $origin != "" && $destination != "" ]]; then
        #file=$(remove_white_spaces "$line")
        #copie "$originPrefix/$origin/$file" "$destination/"
    #fi
done <<< "$intel"

