#!/bin/bash


### PARAMETRES ###

OPTIONS=( 

    "GXY_SAFE" 
    "GXY_MEGASAFE"

)

### INITIALISATION ###

prompt=""
for (( i = 0; i < ${#OPTIONS[@]}; i++ )); do
    if [[ "$(df -Hl | grep "/Volumes/${OPTIONS[$i]}")" != "" ]]; then
        prompt+="$((i+1)): ${OPTIONS[$i]}\n";
    fi
done

if [[ $prompt == "" ]]; then
    printf "ERROR: You have not device plugged in, please plug at least of these:\n"
    for (( i = 0; i < ${#OPTIONS[@]}; i++ )); do
        printf " - ${OPTIONS[$i]}\n";
    done
    exit
elif [[ "$(echo "$prompt" | grep -o "\n" | wc -l)" == "1" ]]; then 
    USB_NAME=${prompt:3:${#prompt}-5}
else
    USB_NAME=""
    while [[ $USB_NAME == "" ]]; do
        printf "$prompt"
        read -r -n 1 resp
        if [[ $resp -ge 1 && $resp -le ${#OPTIONS[@]} ]]; then
            USB_NAME="${OPTIONS[$((resp-1))]}"
        else
            printf "\nError: mauvais input :-)\n"
        fi
    done
fi

echo ""
echo ""
echo "Your files will be synced with \"$USB_NAME\""
echo ""
echo ""

#USB_NAME="GXY_SAFE"

# Gather the intel from files.txt and reformat it (remove comments, remove
# trailing white spaces and remove empty lines)
intel=$(cat "./files.txt" | gsed -e "s/#.*$//;s/\s*$//;/^$/d;")

#originPrefix="$HOME"
destinationPrefix="/Volumes/$USB_NAME"

### FUNCTIONS ###

copie() {
    rsync -rutLa --delete --info=progress2 "$1" "$2" #> "./log"
    #echo cp "$1" "$2"
}

remove_white_spaces(){
    echo "$1" | gsed -e "s/^\s*//;s/\s*$//"
}

### CODE ###

files=()
origin=""
destination=""

while IFS= read -r line;do # go through every line in intel
    origin=$( remove_white_spaces "$line")
    destination=$destinationPrefix"/""${origin##*/}"
    mkdir -p "$destination"
    copie "$origin" "$destination"
done <<< "$intel"

terminal-notifier -title "Backup complete" -message "Your files have been synced to \"$USB_NAME\"" 

