#!/bin/bash


### PARAMETRES ###

#USB_NAME="GXY_SAFE"

# Gather the intel from files.txt and reformat it (remove comments, remove
# trailing white spaces and remove empty lines)
intel=$(cat "./files.txt" | gsed -e "s/#.*$//;s/\s*$//;/^$/d;")

originPrefix="$HOME"
destinationPrefix=$(df -Hl | awk '/GXY_SAFE/ {print $1}')
#destinationPrefix="/tmp/Yann"

### FUNCITON ###

copie() {
    #cp "$1" "$2"
    echo cp "$1" "$2"
}

remove_white_spaces(){
    echo "$1" | sed -e "s/^\s*//;s/\s*$//"
}

### CODE ###

files=()
origin=""
destination=""

while IFS= read -r line;do # go through every line in intel
    # if the line contains "->" it means that it will indicate the origin and
    # the destination of the following files
    if [[ $line == *"->"* ]]; then
        origin=$( remove_white_spaces "$(echo $line | awk -F "->" '{$0=$1}1')")
        destination="$destinationPrefix/"$(remove_white_spaces "$(echo $line | awk -F "->" '{$0=$2}1' | cut -d ":" -f 1)")

        mkdir -p "$destination"
    elif [[ $origin != "" && $destination != "" ]]; then
        file=$(remove_white_spaces "$line")
        copie "$originPrefix/$origin/$file" "$destination/"
    fi
    #if [[ ${line:0:1} == " "]]
done <<< "$intel"

